version: "3.8"

services:
  app:
    image: "periodum_api:${TAG}"
    container_name: periodum_api
    build:
      context: .
      args:
        - NODEJS_VERSION=${NODEJS_VERSION}
        - NODE_ENV=${NODE_ENV}
    volumes:
      - ./src:/usr/app/src
    ports:
      - "127.0.0.1:${NODEJS_PORT}:3000"
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: "mongo:${MONGO_DB_VERSION}"
    container_name: periodum_db
    volumes:
        - ./db/mongodb:/data/db
    restart: unless-stopped
